---
- name: Call tasks for wordpress lift
  include: wordpress.yml
  when: "'{{ profile }}' == 'wordpress'"

- name: Call tasks for custom_sample_app lift
  include: custom_sample_app.yml
  when: "'{{ profile }}' == 'custom_sample_app'"

# other tasks for additional apps ...
