---
- debug:
    msg: "Profile '{{ profile }}' lifting '{{ item }}'"
    verbosity: 2
  with_items: "{{ profiles }}"
  when:
    - "'{{ item.name }}' == '{{ profile }}'"
    - profile is defined

- name: Prep for lifting of application
  include: lift.yml
  when: profile is defined
