---
- name: Profile source hosts
  hosts: source
  roles:
    - role: introspection

- name: Lift and shift application to target container host
  hosts: destination
  roles:
    - role: containerize
    - role: lift_and_shift
