---
- name: Profile source hosts
  hosts: source
  roles:
    - { role: introspect, when: perform_introspection | default (True) }
    - role: lift

- name: Build container and migrate application to target container host
  hosts: destination
  roles:
    - role: shift
