---
- debug:
    var: hostvars['{{ item }}'].profile
    verbosity: 2
  with_items: "{{ groups['source'] }}"

- name: Prep for containerization shift
  include: prep.yml
  vars:
    source_host: "{{ item }}"
  with_items: "{{ groups['source'] }}"
  when: hostvars['{{ item }}'].profile is defined

- name: Shift application into a container
  include: shift.yml
  vars:
    source_host: "{{ item }}"
  with_items: "{{ groups['source'] }}"
  when: hostvars['{{ item }}'].profile is defined
