---
- debug:
    var: hostvars[source_host].profile
    verbosity: 2

- name: Set container version
  set_fact:
    os_major_version: "{{ hostvars[source_host].ansible_distribution_major_version }}"

- name: Set OS name to rhel
  set_fact:
    os_name: "rhel"
  when: "'RedHat' in '{{ hostvars[source_host].ansible_distribution }}'"

- name: Set OS name to centos
  set_fact:
    os_name: "centos"
  when: "'CenOS' in '{{ hostvars[source_host].ansible_distribution }}'"

- name: Set OS name to fedora
  set_fact:
    os_name: "fedora"
  when: "'Fedora' in '{{ hostvars[source_host].ansible_distribution }}'"

- name: Set container name
  set_fact:
    container_name: "{{ hostvars[source_host].profile + '_' + 'shifted_from_' + source_host }}"

- debug:
    var: container_name
    verbosity: 2

- name: Create directory to hold Dockerfile
  file:
    path: ~/{{ container_name }}
    state: directory
    mode: 0755
