---
# List of profiles and matching attributes. These should be unique.
profiles: 
  - name: wordpress
    services:
      - mysqld
      - httpd
    files: []
    dirs:
      - /var/www/html/
    packages:
      - php-mysql
      - mysql
      - mysql-server
  - name: sample_custom_app
    services:
      - postgresql
      - httpd
    files: /etc/sample/sample.conf
    dirs:
      - /svr/sample/
    packages:
      - httpd
      - postgresql-server
      - postgresql
