---
- debug:
    msg: "{{ profile.name }} | Introspecting for dir '{{ item }}'"
    verbosity: 1
  with_items: "{{ profile.dirs }}"

- name: "{{ profile.name }} | Check for detected dirs"
  command: ls -d {{ dir }}
  with_items: "{{ profile.dirs }}"
  register: dirs_status
  ignore_errors: yes
  loop_control:
    loop_var: dir

- name: "{{ profile.name }} | Determine detected dirs"
  debug:
    msg: "dir {{ result.dir }} found enabled"
    verbosity: 1
  with_items: "{{ dirs_status.results }}"
  when: not result.failed | default(None)
  loop_control:
    loop_var: result

- name: "{{ profile.name }} | Initialize list of dirs detected"
  set_fact:
    dirs_detected: []

- name: "{{ profile.name }} | Create list with dirs detected"
  set_fact:
    dirs_detected: "{{ dirs_detected }} + [ '{{ result.dir }}' ]"
  with_items: "{{ dirs_status.results }}"
  when: not result.failed | default(None)
  loop_control:
    loop_var: result

- debug:
    var: dirs_detected
    verbosity: 2

- debug:
    var: profiles_with_matching_dirs
    verbosity: 2

- name: "{{ profile.name }} | Append current profile upon empty list and a match"
  set_fact: 
    profiles_with_matching_dirs: ["{{ profile.name }}"]
  when: 
    - profile.dirs | difference(dirs_detected) == []
    - profiles_with_matching_dirs == []

- name: "{{ profile.name }} | Append current profile with other matched profiles"
  set_fact:
    profiles_with_matching_dirs: "{{ profile_match }} + [ '{{ profile.name }}' ]"
  with_items: profiles_with_matching_dirs
  when:
    - profile.dirs | difference(dirs_detected) == []
    - profiles_with_matching_dirs != []
    - profile_match == profile.name
  loop_control:
    loop_var: profile_match

- debug:
    var: profiles_with_matching_dirs
    verbosity: 2
