---
# tasks file for introspect
- name: Check for running services
  command: service {{ service }} status
  with_items: "{{ services_to_check }}"
  register: services_to_check_status
  ignore_errors: yes
  loop_control:
    loop_var: service

- name: Determine running services
  debug:
    msg: "Service {{ result.service }} found enabled"
    verbosity: 1
  with_items: "{{ services_to_check_status.results }}"
  when: not result.failed | default(None)
  loop_control:
    loop_var: result

- name: Initialize list of services to enable
  set_fact:
    services_to_enable: []

- name: Create list with services to enable
  set_fact:
    services_to_enable: "{{ services_to_enable }} + [ '{{ result.service }}' ]"
  with_items: "{{ services_to_check_status.results }}"
  when: not result.failed | default(None)
  loop_control:
    loop_var: result

- name: Exit if no services were detected
  fail:
    msg: "No services were detected running on the source host of {{ inventory_hostname }}. Nothing to do."
  when: services_to_enable == []

- debug:
    var: services_to_enable

- name: Check for wordpress directory
  command: grep -r "wp-admin/" /var/www/html/
  register: wordpress_exists

- name: Check for php-mysql
  command: rpm -q php-mysql
  register: php_mysql_installed

- name: Set profile to wordpress
  set_fact:
    profile: "wordpress"
  when:
    - "'mysqld' in services_to_enable"
    - "'httpd' in services_to_enable"
    - wordpress_exists.rc == 0
    - php_mysql_installed.rc == 0

# To do - other introspection to determine additional profiles
