---
- set_fact:
    profiles_with_matching_services: []

- name: Match running services to defined application profiles
  include: services.yml
  with_items: "{{ profiles }}"
  loop_control:
    loop_var: profile

- set_fact:
    profiles_with_matching_packages: []

- name: Match installed packages to defined application profiles
  include: packages.yml
  with_items: "{{ profiles }}"
  loop_control:
    loop_var: profile

- set_fact:
    profiles_with_matching_files: []

- name: Match files to defined application profiles
  include: files.yml
  with_items: "{{ profiles }}"
  loop_control:
    loop_var: profile

- set_fact:
    profiles_with_matching_dirs: []

- name: Match directories to defined application profiles
  include: dirs.yml
  with_items: "{{ profiles }}"
  loop_control:
    loop_var: profile

- name: Match profiles
  include: match.yml
  with_items: "{{ profiles }}"
  loop_control:
    loop_var: profile

- debug:
    msg: "Matched profile is '{{ profile }}'"
    verbosity: 1
  when: profile is defined

- name: Exit if no profiles were matched
  fail:
    msg: "No profiles were matched on source host of {{ inventory_hostname }}. Nothing to do."
  when: profile is not defined
