---
- debug:
    msg: "Matching profile '{{ profile.name }}' in '{{ item }}'"
  with_items:
    - "'{{ profiles_with_matching_services }}'"
    - "'{{ profiles_with_matching_packages }}'"
    - "'{{ profiles_with_matching_files }}'"
    - "'{{ profiles_with_matching_dirs }}'"

- name: Check for matching services
  set_fact:
    profile: "{{ profile.name }}"
  when:
    - "'{{ profile.name }}' in profiles_with_matching_services"
    - "'{{ profile.name }}' in profiles_with_matching_packages"
#    - "'{{ profile.name }}' in profiles_with_matching_files"
    - "'{{ profile.name }}' in profiles_with_matching_dirs"

- debug:
    var: profile
    verbosity: 1
