---
- debug:
    msg: "{{ profile.name }} | Introspecting for service '{{ item }}'"
    verbosity: 1
  with_items: "{{ profile.services }}"

- name: "{{ profile.name }} | Check for detected services"
  command: service {{ service }} status
  with_items: "{{ profile.services }}"
  register: services_status
  ignore_errors: yes
  loop_control:
    loop_var: service

- name: "{{ profile.name }} | Determine detected services"
  debug:
    msg: "Service {{ result.service }} found enabled"
    verbosity: 1
  with_items: "{{ services_status.results }}"
  when: not result.failed | default(None)
  loop_control:
    loop_var: result

- name: "{{ profile.name }} | Initialize list of services detected"
  set_fact:
    services_detected: []

- name: "{{ profile.name }} | Create list with services detected"
  set_fact:
    services_detected: "{{ services_detected }} + [ '{{ result.service }}' ]"
  with_items: "{{ services_status.results }}"
  when: not result.failed | default(None)
  loop_control:
    loop_var: result

- debug:
    var: services_detected
    verbosity: 2

- debug:
    var: profiles_with_matching_services
    verbosity: 2

- name: "{{ profile.name }} | Append current profile upon empty list and a match"
  set_fact: 
    profiles_with_matching_services: ["{{ profile.name }}"]
  when: 
    - profile.services | difference(services_detected) == []
    - profiles_with_matching_services == []

- name: "{{ profile.name }} | Append current profile with other matched profiles"
  set_fact:
    profiles_with_matching_services: "{{ profile_match }} + [ '{{ profile.name }}' ]"
  with_items: profiles_with_matching_services
  when:
    - profile.services | difference(services_detected) == []
    - profiles_with_matching_services != []
    - profile_match == profile.name
  loop_control:
    loop_var: profile_match

- debug:
    var: profiles_with_matching_services
    verbosity: 2
