---
# tasks file for containerize
- debug:
    var: hostvars['{{ item }}'].services_to_enable
  with_items: "{{ groups['source'] }}"

- name: Prep for containerization
  include: prep.yml
  vars:
    source_host: "{{ item }}"
  with_items: "{{ groups['source'] }}"
  when: hostvars['{{ item }}'].services_to_enable != []
